name: Doing headless-script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create folder on server
        run: |
       
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S mkdir -p /home/abdul/project/
          cd /home/abdul/
          echo "${{ secrets.SUDO_PASSWORD  }}" | sudo chmod 777 project
          cd /home/abdul/project/
           
      - name: cloning the project
        run: |
          cd /home/abdul/project/
          git init
          git clone https://github.com/abdul-rehman01/project.git
          cd /home/abdul/project/project/
      
      - name: running bash script
        run: |
          bash main.sh

 
