name: Doing headless-script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create folder on server
        run: |
          ssh abdul@147.182.154.10 
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S mkdir -p /home/abdul/project

